# Generated by Django 4.2.15 on 2024-12-09 18:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Analyzer",
            fields=[
                ("analyzer_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("company_name", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=50)),
                ("status", models.BooleanField(default=False)),
                ("MOD_id", models.CharField(max_length=100)),
                ("Date", models.DateField(auto_now_add=True)),
                (
                    "port",
                    models.CharField(
                        choices=[
                            ("com1", "Com1"),
                            ("com2", "Com2"),
                            ("e1", "E1"),
                            ("e2", "E2"),
                        ],
                        max_length=4,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Box",
            fields=[
                ("box", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("content", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                ("device_type", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=200)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("status", models.BooleanField(default=False)),
                ("type", models.CharField(max_length=50)),
                ("value", models.FloatField(default=0.0)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Gateways",
            fields=[
                ("G_id", models.AutoField(primary_key=True, serialize=False)),
                ("gateway_name", models.CharField(max_length=50)),
                ("mac_address", models.CharField(max_length=100, unique=True)),
                ("status", models.BooleanField(default=False)),
                (
                    "deploy_status",
                    models.CharField(
                        choices=[
                            ("warehouse", "In Warehouse"),
                            ("user_aloted", "Alloted to User"),
                            ("deployed", "Deployed to User"),
                        ],
                        default="warehouse",
                        max_length=20,
                    ),
                ),
                ("config", models.BooleanField(default=False)),
                ("analyzers_by_port", models.JSONField(default=dict)),
                (
                    "analyzers",
                    models.ManyToManyField(
                        related_name="gateways", to="ems_app.analyzer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hardware",
            fields=[
                ("hardware_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("serial_number", models.CharField(max_length=100)),
                ("is_connected", models.BooleanField(default=False)),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("firstname", models.CharField(max_length=150)),
                ("lastname", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("contact", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=128)),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Admin"), ("user", "User")],
                        default="user",
                        max_length=20,
                    ),
                ),
                ("image", models.TextField(blank=True, null=True)),
                ("adress", models.CharField(max_length=500)),
                ("is_online", models.BooleanField(default=False)),
                ("zip_code", models.CharField(max_length=10)),
                (
                    "unique_key",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("hardware", models.ManyToManyField(blank=True, to="ems_app.hardware")),
            ],
        ),
        migrations.CreateModel(
            name="User_Project",
            fields=[
                ("up_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "hardware_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ems_app.hardware",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ems_app.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project_Manager",
            fields=[
                ("PM_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("longitude", models.DecimalField(decimal_places=10, max_digits=100)),
                ("latitude", models.DecimalField(decimal_places=10, max_digits=100)),
                ("address", models.CharField(max_length=300)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ems_app.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("project_id", models.AutoField(primary_key=True, serialize=False)),
                ("total_power", models.DecimalField(decimal_places=2, max_digits=10)),
                ("kw", models.DecimalField(decimal_places=2, max_digits=10)),
                ("kva", models.DecimalField(decimal_places=2, max_digits=10)),
                ("power_factor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("frequency", models.DecimalField(decimal_places=2, max_digits=10)),
                ("current_l1", models.DecimalField(decimal_places=2, max_digits=10)),
                ("current_l2", models.DecimalField(decimal_places=2, max_digits=10)),
                ("current_l3", models.DecimalField(decimal_places=2, max_digits=10)),
                ("volt_l1", models.DecimalField(decimal_places=2, max_digits=10)),
                ("volt_l2", models.DecimalField(decimal_places=2, max_digits=10)),
                ("volt_l3", models.DecimalField(decimal_places=2, max_digits=10)),
                ("power_l1", models.DecimalField(decimal_places=2, max_digits=10)),
                ("power_l2", models.DecimalField(decimal_places=2, max_digits=10)),
                ("power_l3", models.DecimalField(decimal_places=2, max_digits=10)),
                ("time", models.TimeField(auto_now=True)),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ems_app.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MetaData",
            fields=[
                ("MD_id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("mac_address", models.CharField(max_length=60)),
                ("MOD_id", models.CharField(max_length=60)),
                (
                    "value1_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "value1_address",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("value1_value", models.FloatField(blank=True, null=True)),
                (
                    "value2_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "value2_address",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("value2_value", models.FloatField(blank=True, null=True)),
                (
                    "value3_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "value3_address",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("value3_value", models.FloatField(blank=True, null=True)),
                (
                    "value4_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "value4_address",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("value4_value", models.FloatField(blank=True, null=True)),
                (
                    "value5_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "value5_address",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("value5_value", models.FloatField(blank=True, null=True)),
                (
                    "value6_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "value6_address",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("value6_value", models.FloatField(blank=True, null=True)),
                (
                    "value7_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "value7_address",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("value7_value", models.FloatField(blank=True, null=True)),
                (
                    "value8_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "value8_address",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("value8_value", models.FloatField(blank=True, null=True)),
                (
                    "value9_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "value9_address",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("value9_value", models.FloatField(blank=True, null=True)),
                (
                    "value10_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "value10_address",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("value10_value", models.FloatField(blank=True, null=True)),
                (
                    "value11_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "value11_address",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("value11_value", models.FloatField(blank=True, null=True)),
                (
                    "value12_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "value12_address",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("value12_value", models.FloatField(blank=True, null=True)),
                (
                    "value13_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "value13_address",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("value13_value", models.FloatField(blank=True, null=True)),
                (
                    "value14_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "value14_address",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("value14_value", models.FloatField(blank=True, null=True)),
                (
                    "value15_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "value15_address",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("value15_value", models.FloatField(blank=True, null=True)),
                (
                    "value16_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "value16_address",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("value16_value", models.FloatField(blank=True, null=True)),
                (
                    "value17_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "value17_address",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("value17_value", models.FloatField(blank=True, null=True)),
                (
                    "value18_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "value18_address",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("value18_value", models.FloatField(blank=True, null=True)),
                (
                    "value19_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "value19_address",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("value19_value", models.FloatField(blank=True, null=True)),
                (
                    "value20_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "value20_address",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("value20_value", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "analyzer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyzer",
                        to="ems_app.analyzer",
                    ),
                ),
                (
                    "gateway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gateways",
                        to="ems_app.gateways",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="hardware",
            name="project_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ems_app.project",
            ),
        ),
        migrations.AddField(
            model_name="gateways",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gateways",
                to="ems_app.project_manager",
            ),
        ),
        migrations.AddField(
            model_name="gateways",
            name="user_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ems_app.user",
            ),
        ),
        migrations.CreateModel(
            name="Gateway",
            fields=[
                ("gateway_id", models.AutoField(primary_key=True, serialize=False)),
                ("gateway_name", models.CharField(max_length=50)),
                (
                    "devices",
                    models.ManyToManyField(
                        related_name="gateways", to="ems_app.device"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="E2",
            fields=[
                ("E2_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "G_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ems_app.gateways",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="E1",
            fields=[
                ("E1_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "G_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ems_app.gateways",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Data",
            fields=[
                ("data_id", models.AutoField(primary_key=True, serialize=False)),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("json_data", models.CharField(max_length=1000)),
                (
                    "project_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ems_app.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Com2",
            fields=[
                ("com2_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "G_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ems_app.gateways",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Com1",
            fields=[
                ("com1_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "G_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ems_app.gateways",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="analyzer",
            name="gateway",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ems_app.gateways"
            ),
        ),
    ]
