# Generated by Django 4.2.15 on 2024-12-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ems_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analyzer",
            name="port",
            field=models.CharField(
                choices=[
                    ("com_1", "Com1"),
                    ("com_2", "Com2"),
                    ("e1", "E1"),
                    ("e2", "E2"),
                ],
                max_length=6,
            ),
        ),
    ]
