# Generated by Django 4.2.15 on 2024-08-21 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ems_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("project_id", models.AutoField(primary_key=True, serialize=False)),
                ("total_power", models.DecimalField(decimal_places=2, max_digits=10)),
                ("kw", models.DecimalField(decimal_places=2, max_digits=10)),
                ("kva", models.DecimalField(decimal_places=2, max_digits=10)),
                ("power_fector", models.DecimalField(decimal_places=2, max_digits=10)),
                ("frequency", models.DecimalField(decimal_places=2, max_digits=10)),
                ("current_l1", models.DecimalField(decimal_places=2, max_digits=10)),
                ("current_l2", models.DecimalField(decimal_places=2, max_digits=10)),
                ("current_l3", models.DecimalField(decimal_places=2, max_digits=10)),
                ("volt_l1", models.DecimalField(decimal_places=2, max_digits=10)),
                ("volt_l2", models.DecimalField(decimal_places=2, max_digits=10)),
                ("volt_l3", models.DecimalField(decimal_places=2, max_digits=10)),
                ("power_l1", models.DecimalField(decimal_places=2, max_digits=10)),
                ("power_l2", models.DecimalField(decimal_places=2, max_digits=10)),
                ("power_l3", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ems_app.user"
                    ),
                ),
            ],
        ),
    ]
