# Generated by Django 4.2.20 on 2025-05-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ems_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="adress",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="zip_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
