# Generated by Django 4.2.15 on 2024-08-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ems_app", "0002_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hardware",
            fields=[
                ("hardware_id", models.AutoField(primary_key=True, serialize=False)),
                ("hardware_name", models.CharField(max_length=200)),
                ("is_connected", models.BooleanField(default=False)),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
