# Generated by Django 5.1.7 on 2025-03-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0002_alter_analyzer_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='setpoint1',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='metadata',
            name='setpoint2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='metadata',
            name='total_power',
            field=models.FloatField(default=0.0),
        ),
    ]
