# Generated by Django 4.2.15 on 2024-08-26 14:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ems_app", "0003_hardware"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Hardware",
        ),
    ]
