# Generated by Django 5.1.7 on 2025-03-27 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0003_metadata_setpoint1_metadata_setpoint2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadata',
            name='setpoint1',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='setpoint2',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='total_power',
        ),
    ]
