# Generated by Django 5.1.7 on 2025-03-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0004_remove_metadata_setpoint1_remove_metadata_setpoint2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='setpoint1',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='metadata',
            name='setpoint2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='metadata',
            name='total_power',
            field=models.FloatField(default=0.0),
        ),
    ]
