# Generated by Django 5.1.7 on 2025-04-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0005_metadata_setpoint1_metadata_setpoint2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='total_Generator',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='metadata',
            name='total_grid',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='metadata',
            name='total_solar',
            field=models.FloatField(default=0.0),
        ),
    ]
