# Generated by Django 4.2.15 on 2024-08-26 14:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ems_app", "0005_hardware"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hardware",
            name="project_id",
        ),
    ]
