# Generated by Django 4.2.15 on 2024-08-27 07:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ems_app", "0006_remove_hardware_project_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Hardware",
        ),
    ]
