# Generated by Django 5.1.7 on 2025-04-05 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0007_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='last_updated',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='time',
        ),
    ]
