# Generated by Django 4.2.15 on 2024-08-27 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ems_app", "0007_delete_hardware"),
    ]

    operations = [
        migrations.CreateModel(
            name="Haedware",
            fields=[
                ("hardware_id", models.AutoField(primary_key=True, serialize=False)),
                ("hardware_name", models.CharField(max_length=100)),
                ("is_connected", models.BooleanField(default=False)),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "Project_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ems_app.project",
                    ),
                ),
            ],
        ),
    ]
