# Generated by Django 4.2.15 on 2024-08-27 07:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ems_app", "0008_haedware"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Haedware",
            new_name="Hardware",
        ),
    ]
