# Generated by Django 5.2 on 2025-04-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0008_rename_last_updated_subscription_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='admincr',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('cr_id', models.CharField(max_length=20)),
                ('admin_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='superadmincr',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('superadmin_id', models.CharField(max_length=20)),
                ('admin_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('superadmin', 'superadmin')], default='user', max_length=20),
        ),
    ]
