# Generated by Django 4.2.15 on 2024-08-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ems_app", "0009_rename_haedware_hardware"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="time",
            field=models.TimeField(auto_now=True),
        ),
    ]
