# Generated by Django 5.2 on 2025-04-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0009_admincr_superadmincr_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
