# Generated by Django 4.2.15 on 2024-08-29 09:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("ems_app", "0010_project_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="power_fector",
            new_name="power_factor",
        ),
        migrations.AddField(
            model_name="project",
            name="last_updated",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
