# Generated by Django 5.2 on 2025-04-09 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0010_subscription_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='total_price',
        ),
    ]
