# Generated by Django 5.2 on 2025-04-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0011_remove_subscription_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='timestamp',
            new_name='Active_date',
        ),
        migrations.AddField(
            model_name='subscription',
            name='deactive',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
