# Generated by Django 4.2.15 on 2024-08-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ems_app", "0011_rename_power_fector_project_power_factor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
