# Generated by Django 4.2.15 on 2024-08-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ems_app", "0012_alter_project_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="time",
            field=models.TimeField(auto_now=True),
        ),
    ]
