# Generated by Django 5.2 on 2025-04-09 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0012_rename_timestamp_subscription_active_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceTable',
            fields=[
                ('inv_id', models.AutoField(primary_key=True, serialize=False)),
                ('active_date', models.DateTimeField()),
                ('warn_date', models.DateField()),
                ('days_left', models.IntegerField()),
                ('end_date', models.DateField()),
                ('billing_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Overdue', 'Overdue')], default='Pending', max_length=20)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ems_app.subscription')),
            ],
        ),
    ]
