# Generated by Django 5.2 on 2025-04-09 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0013_invoicetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='InvoiceTable',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
