# Generated by Django 4.2.15 on 2024-09-05 06:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ems_app", "0013_alter_project_time"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Hardware",
        ),
    ]
