# Generated by Django 5.2 on 2025-04-09 23:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0014_remove_subscription_user_id_delete_invoicetable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('warn_date', models.DateField(blank=True, null=True)),
                ('stop_date', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('Active_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('deactive', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ems_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceTable',
            fields=[
                ('inv_id', models.AutoField(primary_key=True, serialize=False)),
                ('active_date', models.DateTimeField()),
                ('warn_date', models.DateField()),
                ('days_left', models.IntegerField()),
                ('end_date', models.DateField()),
                ('billing_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Overdue', 'Overdue')], default='Pending', max_length=20)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ems_app.subscription')),
            ],
        ),
    ]
