# Generated by Django 5.2 on 2025-04-10 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0015_subscription_invoicetable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicetable',
            old_name='active_date',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='invoicetable',
            name='days_left',
        ),
        migrations.RemoveField(
            model_name='invoicetable',
            name='warn_date',
        ),
    ]
