# Generated by Django 5.2 on 2025-04-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0016_rename_active_date_invoicetable_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deactive', 'Deactive')], default='Deactive', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='Active_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='deactive',
            field=models.DateField(blank=True, null=True),
        ),
    ]
