# Generated by Django 4.2.15 on 2024-09-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ems_app", "0017_user_up_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="up_id",
        ),
        migrations.AddField(
            model_name="user_project",
            name="name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
