# Generated by Django 5.2 on 2025-04-11 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0017_subscription_status_alter_subscription_active_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='stop_date',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='warn_date',
        ),
    ]
