# Generated by Django 5.2 on 2025-04-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0018_remove_subscription_stop_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='stop_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='subscription',
            name='warn_days',
            field=models.IntegerField(default=30),
        ),
    ]
