# Generated by Django 4.2.15 on 2024-09-05 11:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ems_app", "0018_remove_user_up_id_user_project_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User_Project",
        ),
    ]
