# Generated by Django 5.2 on 2025-04-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ems_app", "0019_subscription_stop_days_subscription_warn_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoicetable",
            name="start_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.CharField(blank=True, null=True),
        ),
    ]
