# Generated by Django 4.2.15 on 2024-09-05 11:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ems_app", "0020_user_project"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User_Project",
        ),
    ]
