# Generated by Django 5.2 on 2025-04-18 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ems_app", "0021_user_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="project_manager",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_project_managers",
                to="ems_app.user",
            ),
        ),
    ]
