# Generated by Django 4.2.15 on 2024-09-05 11:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ems_app", "0022_user_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user_project",
            name="project_id",
        ),
        migrations.RemoveField(
            model_name="user_project",
            name="user_id",
        ),
        migrations.DeleteModel(
            name="Hardware",
        ),
        migrations.DeleteModel(
            name="User_Project",
        ),
    ]
