# Generated by Django 5.2 on 2025-04-18 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ems_app", "0022_project_manager_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project_manager",
            name="created_by",
        ),
    ]
