# Generated by Django 4.2.20 on 2025-04-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ems_app", "0023_remove_project_manager_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
