# Generated by Django 4.2.15 on 2024-09-05 12:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ems_app", "0024_user_project_hardware"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user_project",
            name="name",
        ),
    ]
