# Generated by Django 4.2.20 on 2025-04-21 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ems_app", "0024_alter_user_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="gateways",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_users",
                to="ems_app.gateways",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
