# Generated by Django 4.2.20 on 2025-04-21 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ems_app", "0025_gateways_created_by_alter_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gateways",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_gateways",
                to="ems_app.user",
            ),
        ),
    ]
