# Generated by Django 4.2.15 on 2024-09-05 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ems_app", "0025_remove_user_project_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="up_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="ems_app.user_project",
            ),
            preserve_default=False,
        ),
    ]
