# Generated by Django 4.2.20 on 2025-04-21 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ems_app", "0026_alter_gateways_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gateways",
            name="created_by",
        ),
    ]
