# Generated by Django 4.2.15 on 2024-09-05 13:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ems_app", "0026_user_up_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hardware",
            name="user_id",
        ),
    ]
