# Generated by Django 4.2.20 on 2025-04-21 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ems_app", "0027_remove_gateways_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="gateways",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_users",
                to="ems_app.gateways",
            ),
        ),
    ]
