# Generated by Django 4.2.15 on 2024-09-05 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ems_app", "0027_remove_hardware_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="hardware_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="ems_app.hardware",
            ),
            preserve_default=False,
        ),
    ]
