# Generated by Django 4.2.15 on 2024-09-05 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ems_app", "0028_project_hardware_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                ("data_id", models.AutoField(primary_key=True, serialize=False)),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("json_data", models.CharField(max_length=1000)),
                (
                    "project_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ems_app.project",
                    ),
                ),
            ],
        ),
    ]
