# Generated by Django 4.2.20 on 2025-04-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ems_app", "0028_gateways_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gateways",
            name="created_by",
        ),
        migrations.AddField(
            model_name="gateways",
            name="created_by_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
