# Generated by Django 4.2.20 on 2025-04-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ems_app", "0029_remove_gateways_created_by_gateways_created_by_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gateways",
            name="created_by_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
