# Generated by Django 4.2.20 on 2025-04-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ems_app", "0030_alter_gateways_created_by_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="metadata",
            name="value10_unit",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metadata",
            name="value11_unit",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metadata",
            name="value12_unit",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metadata",
            name="value13_unit",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metadata",
            name="value14_unit",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metadata",
            name="value15_unit",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metadata",
            name="value16_unit",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metadata",
            name="value17_unit",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metadata",
            name="value18_unit",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metadata",
            name="value19_unit",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metadata",
            name="value1_unit",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metadata",
            name="value20_unit",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metadata",
            name="value2_unit",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metadata",
            name="value3_unit",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metadata",
            name="value4_unit",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metadata",
            name="value5_unit",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metadata",
            name="value6_unit",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metadata",
            name="value7_unit",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metadata",
            name="value8_unit",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metadata",
            name="value9_unit",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
