# Generated by Django 4.2.15 on 2024-09-06 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ems_app", "0030_user_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="up_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ems_app.user_project",
            ),
        ),
    ]
