# Generated by Django 4.2.20 on 2025-04-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ems_app", "0031_metadata_value10_unit_metadata_value11_unit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metadata",
            name="value10_unit",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="metadata",
            name="value11_unit",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="metadata",
            name="value12_unit",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="metadata",
            name="value13_unit",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="metadata",
            name="value14_unit",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="metadata",
            name="value15_unit",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="metadata",
            name="value16_unit",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="metadata",
            name="value17_unit",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="metadata",
            name="value18_unit",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="metadata",
            name="value19_unit",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="metadata",
            name="value1_unit",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="metadata",
            name="value20_unit",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="metadata",
            name="value2_unit",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="metadata",
            name="value3_unit",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="metadata",
            name="value4_unit",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="metadata",
            name="value5_unit",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="metadata",
            name="value6_unit",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="metadata",
            name="value7_unit",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="metadata",
            name="value8_unit",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="metadata",
            name="value9_unit",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
