# Generated by Django 4.2.15 on 2024-09-06 13:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ems_app", "0034_remove_project_hardware_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hardware",
            name="project_id",
        ),
    ]
