# Generated by Django 4.2.15 on 2024-09-06 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ems_app", "0035_remove_hardware_project_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="hardware",
            name="project_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="ems_app.project",
            ),
            preserve_default=False,
        ),
    ]
